import '../styles/globals.css'
import {MoralisProvider} from "react-moralis"
import Header from './components/Header'
import Head from 'next/head'
import {NotificationProvider} from "web3uikit"

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoralisProvider initializeOnMount={false}>
        <NotificationProvider>
          <Header />
          <Component {...pageProps} />
        </NotificationProvider>
      </MoralisProvider>
    </>
  )
}

export default MyApp
